# Generated by Django 3.0.3 on 2020-03-10 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0002_auto_20200310_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_room_name', models.CharField(max_length=20)),
                ('lecture_room_code', models.CharField(max_length=20)),
                ('beacon_uuid', models.CharField(max_length=30)),
                ('beacon_major', models.CharField(max_length=30)),
                ('beacon_minor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=30)),
                ('subject_code', models.CharField(max_length=20)),
                ('split_code', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('prof_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='professor.Professor')),
            ],
        ),
    ]
