# Generated by Django 3.0.3 on 2020-03-18 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_auto_20200318_1522'),
        ('lecture', '0002_auto_20200310_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon_uuid', models.CharField(max_length=30)),
                ('beacon_major', models.CharField(max_length=30)),
                ('beacon_minor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('split_code', models.CharField(max_length=10)),
                ('semester', models.IntegerField()),
                ('prof_code', models.ForeignKey(db_column='prof_code', on_delete=django.db.models.deletion.CASCADE, to='professor.Professor', to_field='prof_code')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('room_code', models.CharField(max_length=20, unique=True)),
                ('building', models.CharField(max_length=20)),
                ('room_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='LectureRoom',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='lecture',
            name='room_code',
            field=models.ForeignKey(db_column='room_code', on_delete=django.db.models.deletion.CASCADE, to='lecture.Room', to_field='room_code'),
        ),
        migrations.AddField(
            model_name='beacon',
            name='room_code',
            field=models.OneToOneField(db_column='room_code', on_delete=django.db.models.deletion.CASCADE, to='lecture.Room', to_field='room_code'),
        ),
    ]
