# Generated by Django 2.0.13 on 2020-03-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0004_auto_20200318_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='lecture_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='강의 코드'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='name',
            field=models.CharField(max_length=30, verbose_name='강의명'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='semester',
            field=models.IntegerField(verbose_name='학기'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='split_code',
            field=models.CharField(max_length=10, verbose_name='분반 코드'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.CharField(max_length=20, verbose_name='동'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='강의실 코드'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=20, verbose_name='호수'),
        ),
    ]
