# Generated by Django 2.0.13 on 2020-03-24 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_auto_20200322_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beacon',
            name='beacon_uuid',
        ),
    ]
