# Generated by Django 2.0.13 on 2020-03-26 07:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0006_remove_beacon_beacon_uuid'),
    ]
