# Generated by Django 2.0.13 on 2020-03-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0007_lecture_day_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='day_of_the_week',
            field=models.CharField(max_length=10, null=True, verbose_name='수업 요일'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='end_time',
            field=models.TimeField(default='00:00', verbose_name='수업 종료 시간'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='start_time',
            field=models.TimeField(default='00:00', verbose_name='수업 시작 시간'),
        ),
    ]
