# Generated by Django 2.0.13 on 2020-04-13 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0008_auto_20200328_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='lecture_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='room_number',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='beacon',
            name='beacon_major',
        ),
        migrations.RemoveField(
            model_name='beacon',
            name='beacon_minor',
        ),
        migrations.AddField(
            model_name='beacon',
            name='major',
            field=models.CharField(default='컴퓨터공학과', max_length=10, verbose_name='비콘 major 값'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='beacon',
            name='minor',
            field=models.CharField(default=44, max_length=10, verbose_name='비콘 minor 값'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beacon',
            name='room_code',
            field=models.OneToOneField(db_column='room_code', on_delete=django.db.models.deletion.CASCADE, to='lecture.Room', to_field='code', verbose_name='강의실 코드'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='prof_code',
            field=models.ForeignKey(db_column='prof_code', on_delete=django.db.models.deletion.CASCADE, to='professor.Professor', to_field='code', verbose_name='교수 코드'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='room_code',
            field=models.ForeignKey(db_column='room_code', on_delete=django.db.models.deletion.CASCADE, to='lecture.Room', to_field='code'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='semester',
            field=models.IntegerField(choices=[('1st_semester', '1'), ('Seconde_semester', '2')], verbose_name='학기'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='split_code',
            field=models.CharField(choices=[('AM', 'z1'), ('PM', 'z2')], max_length=3, verbose_name='분반 코드'),
        ),
    ]
