# Generated by Django 2.0.13 on 2020-04-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0010_hi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hi',
        ),
    ]
