# Generated by Django 2.0.13 on 2020-04-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0012_remove_lecture_prof_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='semester',
            field=models.CharField(choices=[('1st_semester', '1'), ('Seconde_semester', '2')], max_length=20, verbose_name='학기'),
        ),
    ]
