# Generated by Django 2.0.13 on 2020-04-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0022_auto_20200414_1713'),
        ('lecture', '0013_auto_20200414_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='professor',
            field=models.ManyToManyField(to='professor.Professor', verbose_name='교수'),
        ),
    ]
