# Generated by Django 2.0.13 on 2020-04-16 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0022_auto_20200414_1713'),
        ('lecture', '0014_lecture_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveLectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='lecture',
            name='professor',
            field=models.ManyToManyField(through='lecture.GiveLectures', to='professor.Professor', verbose_name='교수'),
        ),
        migrations.AddField(
            model_name='givelectures',
            name='lectures',
            field=models.ForeignKey(db_column='lectures', on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture', to_field='code', verbose_name='수강 강의'),
        ),
        migrations.AddField(
            model_name='givelectures',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='professor.Professor', to_field='username', verbose_name='학번'),
        ),
    ]
