# Generated by Django 2.0.13 on 2020-04-16 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0015_auto_20200416_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='professor',
            new_name='give_lectures',
        ),
        migrations.AlterField(
            model_name='givelectures',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='professor.Professor', to_field='username', verbose_name='교수'),
        ),
    ]
