# Generated by Django 2.0.13 on 2020-04-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0016_auto_20200416_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='givelectures',
            name='lectures',
        ),
        migrations.RemoveField(
            model_name='givelectures',
            name='username',
        ),
        migrations.AlterField(
            model_name='lecture',
            name='give_lectures',
            field=models.ManyToManyField(to='professor.Professor', verbose_name='교수'),
        ),
        migrations.DeleteModel(
            name='GiveLectures',
        ),
    ]
