# Generated by Django 2.0.13 on 2020-04-16 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0017_auto_20200416_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='give_lectures',
            new_name='professor',
        ),
    ]
