# Generated by Django 2.0.13 on 2020-04-16 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0018_auto_20200416_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='professor',
        ),
    ]
