# Generated by Django 2.0.13 on 2020-04-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0022_auto_20200414_1713'),
        ('lecture', '0019_remove_lecture_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiveLectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectures', models.ForeignKey(db_column='lectures', on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture', to_field='code', verbose_name='수강 강의')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='professor.Professor', to_field='username', verbose_name='교수')),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='professor',
            field=models.ManyToManyField(through='lecture.GiveLectures', to='professor.Professor', verbose_name='교수'),
        ),
    ]
