# Generated by Django 2.0.13 on 2020-04-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0020_auto_20200416_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givelectures',
            name='lectures',
            field=models.ForeignKey(db_column='lectures', on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture', verbose_name='담당 강의'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='code',
            field=models.CharField(max_length=20, verbose_name='강의 코드'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='split_code',
            field=models.CharField(max_length=3, unique=True, verbose_name='분반 코드'),
        ),
    ]
