# Generated by Django 2.0.13 on 2020-04-18 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0021_auto_20200418_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='givelectures',
            name='lectures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture', verbose_name='담당 강의'),
        ),
    ]
