# Generated by Django 2.0.13 on 2020-04-18 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0022_auto_20200418_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='code',
        ),
    ]
