# Generated by Django 2.0.13 on 2020-04-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0023_remove_lecture_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='code',
            field=models.CharField(default=None, max_length=20, verbose_name='강의 코드'),
            preserve_default=False,
        ),
    ]
