# Generated by Django 2.0.13 on 2020-05-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0024_lecture_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='uuid',
            field=models.CharField(max_length=50, null=True, verbose_name='비콘 UUID 값'),
        ),
    ]
