# Generated by Django 2.0.13 on 2020-05-15 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0025_beacon_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='uuid',
            field=models.OneToOneField(db_column='uuid', limit_choices_to={'level': 1}, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.College', to_field='uuid', verbose_name='학교와 대응되는 비콘 UUID 값'),
        ),
    ]
