# Generated by Django 2.0.13 on 2020-05-15 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0026_auto_20200515_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='uuid',
            field=models.ForeignKey(db_column='uuid', limit_choices_to={'level': 0}, max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.College', to_field='uuid', verbose_name='학교와 대응되는 비콘 UUID 값'),
        ),
    ]
