# Generated by Django 2.0.13 on 2020-05-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0027_auto_20200515_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='count',
            field=models.IntegerField(max_length=5, null=True, verbose_name='반복 횟수'),
        ),
        migrations.AddField(
            model_name='lecture',
            name='term',
            field=models.CharField(choices=[('15', '15'), ('30', '30'), ('45', '45'), ('60', '60')], default='30', max_length=5, verbose_name='출석 반복 시간'),
        ),
    ]
