# Generated by Django 2.0.13 on 2020-05-18 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0028_auto_20200518_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='count',
            field=models.IntegerField(null=True, verbose_name='반복 횟수'),
        ),
    ]
