# Generated by Django 3.0.7 on 2020-08-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0029_auto_20200518_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='camera',
            field=models.GenericIPAddressField(null=True, verbose_name='ip카메라'),
        ),
    ]
