# Generated by Django 2.0.13 on 2020-05-17 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, null=True, unique=True, verbose_name='교수 코드')),
                ('major', models.ForeignKey(db_column='major', null=True, on_delete=django.db.models.deletion.PROTECT, to='university.College', to_field='name', verbose_name='소속')),
                ('username', models.OneToOneField(db_column='username', limit_choices_to={'groups__name': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
