# Generated by Django 3.0.3 on 2020-03-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_auto_20200310_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='prof_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
