# Generated by Django 3.0.3 on 2020-03-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0003_auto_20200310_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='major',
            new_name='major_code',
        ),
    ]
