# Generated by Django 2.0.13 on 2020-03-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0004_auto_20200318_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='major_code',
            field=models.CharField(max_length=30, verbose_name='학과 코드'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='prof_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='교수 코드'),
        ),
    ]
