# Generated by Django 2.0.13 on 2020-04-04 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20200322_1831'),
        ('professor', '0005_auto_20200322_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='major_code',
        ),
        migrations.AddField(
            model_name='professor',
            name='major',
            field=models.ForeignKey(db_column='major', null=True, on_delete=django.db.models.deletion.PROTECT, to='university.College', to_field='name', verbose_name='소속학과'),
        ),
    ]
