# Generated by Django 2.0.13 on 2020-04-13 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professor', '0006_auto_20200404_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='prof_code',
            new_name='code',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='user',
        ),
        migrations.AddField(
            model_name='professor',
            name='username',
            field=models.OneToOneField(db_column='username', default=0, limit_choices_to={'groups__name': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
