# Generated by Django 2.0.13 on 2020-04-13 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0007_auto_20200413_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='username',
            field=models.OneToOneField(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
