# Generated by Django 2.0.13 on 2020-04-14 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0008_auto_20200413_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='hi',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
