# Generated by Django 2.0.13 on 2020-04-14 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0009_professor_hi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='major',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='username',
        ),
    ]
