# Generated by Django 2.0.13 on 2020-04-14 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0010_auto_20200414_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='code',
        ),
    ]
