# Generated by Django 2.0.13 on 2020-04-14 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0011_remove_professor_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
