# Generated by Django 2.0.13 on 2020-04-14 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0004_auto_20200322_1831'),
        ('professor', '0012_delete_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='교수 코드')),
                ('hi', models.CharField(max_length=20, null=True)),
                ('major', models.ForeignKey(db_column='major', null=True, on_delete=django.db.models.deletion.PROTECT, to='university.College', to_field='name', verbose_name='소속학과')),
            ],
        ),
    ]
