# Generated by Django 2.0.13 on 2020-04-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0013_professor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professor',
            old_name='major',
            new_name='major_code',
        ),
    ]
