# Generated by Django 2.0.13 on 2020-04-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0015_remove_professor_major_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='bye',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
