# Generated by Django 2.0.13 on 2020-04-14 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20200322_1831'),
        ('professor', '0016_professor_bye'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='major_code',
            field=models.ForeignKey(db_column='major', null=True, on_delete=django.db.models.deletion.PROTECT, to='university.College', to_field='name', verbose_name='소속학과'),
        ),
    ]
