# Generated by Django 2.0.13 on 2020-04-14 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professor', '0017_professor_major_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='username',
            field=models.OneToOneField(db_column='username', default='00000000', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
    ]
