# Generated by Django 2.0.13 on 2020-04-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0020_remove_professor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='code',
            field=models.CharField(default='PROF001', max_length=20, unique=True, verbose_name='교수 코드'),
        ),
    ]
