# Generated by Django 2.0.13 on 2020-04-14 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0021_professor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='code',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='교수 코드'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='username',
            field=models.OneToOneField(db_column='username', limit_choices_to={'groups__name': 'professor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
