# Generated by Django 2.0.13 on 2020-05-17 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('FRESHMAN', '1'), ('SOPHOMORE', '2'), ('JUNIOR', '3'), ('SENIOR', '4')], max_length=10, verbose_name='학년')),
                ('photo', models.ImageField(null=True, storage=student.models.OverwriteStorage(), upload_to=student.models.user_photo_path, verbose_name='사진')),
                ('major', models.ForeignKey(db_column='major', limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, to='university.College', to_field='name', verbose_name='학과')),
            ],
        ),
        migrations.CreateModel(
            name='TakeLectures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture', verbose_name='수강 강의')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='student.Student', to_field='username', verbose_name='학번')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='take_lectures',
            field=models.ManyToManyField(through='student.TakeLectures', to='lecture.Lecture', verbose_name='수강 강의'),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.OneToOneField(db_column='username', limit_choices_to={'groups__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='학번'),
        ),
    ]
