# Generated by Django 2.2.6 on 2020-03-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20200318_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
