# Generated by Django 2.0.13 on 2020-03-22 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0004_auto_20200322_1831'),
        ('student', '0005_auto_20200322_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='major_code',
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.ForeignKey(db_column='major', null=True, on_delete=django.db.models.deletion.PROTECT, to='university.College', to_field='name'),
        ),
    ]
