# Generated by Django 2.2.6 on 2020-03-23 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_face'),
        ('student', '0006_auto_20200322_1831'),
    ]

    operations = [
    ]
