# Generated by Django 2.0.13 on 2020-03-24 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0005_auto_20200322_1738'),
        ('student', '0006_auto_20200322_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='lecture',
            field=models.ManyToManyField(to='lecture.Lecture', verbose_name='수강 강의'),
        ),
        migrations.AlterField(
            model_name='enroll',
            name='user',
            field=models.ForeignKey(db_column='user', limit_choices_to={'groups__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='학번'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(db_column='major', limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, to='university.College', to_field='name', verbose_name='학과'),
        ),
    ]
