# Generated by Django 2.2.6 on 2020-03-23 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_merge_20200323_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='face',
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(db_column='major', limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, to='university.College', to_field='name'),
        ),
    ]
