# Generated by Django 2.0.13 on 2020-03-24 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200324_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='lecture',
            new_name='lecture_list',
        ),
    ]
