# Generated by Django 2.2.6 on 2020-03-24 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20200324_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(db_column='major', limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.PROTECT, to='university.College', to_field='name', verbose_name='학과'),
        ),
    ]
