# Generated by Django 2.0.13 on 2020-04-13 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0009_auto_20200404_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='enroll',
            name='username',
            field=models.ForeignKey(db_column='username', default='test', limit_choices_to={'groups__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='학번'),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.OneToOneField(db_column='username', default=0, limit_choices_to={'groups__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='학번'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.CharField(choices=[('FRESHMAN', '1'), ('SOPHOMORE', '2'), ('JUNIOR', '3'), ('SENIOR', '4')], max_length=10, verbose_name='학년'),
        ),
    ]
