# Generated by Django 2.2.6 on 2020-03-26 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20200324_1441'),
        ('student', '0008_auto_20200324_1806'),
    ]

    operations = [
    ]
