# Generated by Django 2.0.13 on 2020-04-13 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20200413_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='username',
            field=models.ForeignKey(db_column='username', default='admin', on_delete=django.db.models.deletion.CASCADE, to='student.Student', to_field='username', verbose_name='학번'),
        ),
    ]
