# Generated by Django 2.0.13 on 2020-04-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20200414_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='lecture',
        ),
        migrations.RemoveField(
            model_name='enroll',
            name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='lecture_list',
        ),
        migrations.AddField(
            model_name='enroll',
            name='hi',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
