# Generated by Django 2.0.13 on 2020-04-14 06:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lecture', '0011_delete_hi'),
        ('student', '0016_auto_20200414_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enroll',
            name='hi',
        ),
        migrations.AddField(
            model_name='enroll',
            name='lecture_list',
            field=models.ManyToManyField(to='lecture.Lecture', verbose_name='수강 강의'),
        ),
        migrations.AddField(
            model_name='enroll',
            name='user',
            field=models.ForeignKey(db_column='user', default='00000000', limit_choices_to={'groups__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='학번'),
            preserve_default=False,
        ),
    ]
