# Generated by Django 2.0.13 on 2020-04-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0018_auto_20200414_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hi', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
