# Generated by Django 2.0.13 on 2020-04-14 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_enroll'),
    ]

    operations = [
        migrations.DeleteModel(
            name='enroll',
        ),
    ]
