# Generated by Django 2.0.13 on 2020-04-14 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20200414_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takelectures',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='student.Student', to_field='username', verbose_name='학번'),
        ),
    ]
