# Generated by Django 2.0.13 on 2020-04-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_auto_20200416_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takelectures',
            name='lectures',
            field=models.ForeignKey(db_column='lectures', on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture', verbose_name='수강 강의'),
        ),
        migrations.AlterField(
            model_name='takelectures',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='student.Student', to_field='username', verbose_name='학번'),
        ),
    ]
