# Generated by Django 2.0.13 on 2020-05-15 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_auto_20200418_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(db_column='major', limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.College', to_field='name', verbose_name='학과'),
        ),
        migrations.AlterField(
            model_name='takelectures',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='student.Student', to_field='username', verbose_name='학번'),
        ),
    ]
