# Generated by Django 2.0.13 on 2020-05-15 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_auto_20200515_1542'),
        ('student', '0027_auto_20200515_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='college',
            field=models.OneToOneField(db_column='college', limit_choices_to={'level': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='college', to='university.College', to_field='name', verbose_name='소속(학교)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='major',
            field=models.ForeignKey(db_column='major', limit_choices_to={'level': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='major', to='university.College', to_field='name', verbose_name='학과'),
        ),
        migrations.AlterField(
            model_name='takelectures',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='student.Student', to_field='username', verbose_name='학번'),
        ),
    ]
