# Generated by Django 2.0.13 on 2020-03-22 09:23

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_auto_20200322_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='college',
            name='college_name',
        ),
        migrations.AddField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='대학(학과) 이름'),
        ),
        migrations.AlterField(
            model_name='college',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='university.College', verbose_name='대학 선택'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
