# Generated by Django 2.0.13 on 2020-03-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_auto_20200322_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='대학(학과) 이름'),
        ),
    ]
