# Generated by Django 2.0.13 on 2020-05-13 05:20

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='college',
        ),
        migrations.AlterField(
            model_name='college',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='college',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='university.College', verbose_name='소속'),
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
