# Generated by Django 2.0.13 on 2020-05-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0007_auto_20200513_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='uuid',
            field=models.CharField(max_length=50, null=True, verbose_name='학교 구분을 위한 uuid'),
        ),
    ]
