# Generated by Django 2.0.13 on 2020-05-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0008_college_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='uuid',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='학교 구분을 위한 uuid'),
        ),
    ]
