# Generated by Django 2.0.13 on 2020-05-15 06:34

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_auto_20200515_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='university.College', verbose_name='소속'),
        ),
    ]
