# Generated by Django 2.0.13 on 2020-04-13 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0004_auto_20200325_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.AddField(
            model_name='attendance',
            name='username',
            field=models.ForeignKey(db_column='username', default=0, limit_choices_to={'groups__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='lecture_code',
            field=models.ForeignKey(db_column='lecture_code', on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture', to_field='code'),
        ),
    ]
