# Generated by Django 2.0.13 on 2020-04-14 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20200413_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='username',
            new_name='user',
        ),
    ]
