# Generated by Django 2.0.13 on 2020-04-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_auto_20200414_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='user',
            new_name='username',
        ),
    ]
