# Generated by Django 2.0.13 on 2020-04-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20200414_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
