# Generated by Django 2.0.13 on 2020-04-18 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0021_auto_20200418_1414'),
        ('attendance', '0008_auto_20200416_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='lecture_code',
        ),
        migrations.AddField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(db_column='lecture_code', default='----', on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture'),
        ),
    ]
