# Generated by Django 2.0.13 on 2020-04-18 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_auto_20200418_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture'),
        ),
    ]
