# Generated by Django 2.0.13 on 2020-04-20 07:59

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_attendance_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='result',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
