# Generated by Django 2.0.13 on 2020-06-15 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0029_auto_20200518_1328'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0015_attendance_final_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='facial_attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True)),
                ('result', jsonfield.fields.JSONField(default=dict)),
                ('final_result', models.CharField(default='처리중', max_length=10)),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
                ('username', models.ForeignKey(db_column='username', limit_choices_to={'groups__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
