# Generated by Django 2.0.13 on 2020-06-22 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0029_auto_20200518_1328'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0016_facial_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('check', models.CharField(max_length=5, verbose_name='in/out')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.Lecture')),
                ('username', models.ForeignKey(db_column='username', limit_choices_to={'groups__name': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
