# Generated by Django 3.0.7 on 2020-09-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_userlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
